// Run this once locally with: node convert-font.js
// It reads a downloaded .ttf file and writes a .ts file jsPDF can use.

const fs = require("fs");
const path = require("path");

const fontPath = path.join(__dirname, "NotoSansOlChiki-Regular.ttf");
const outPath = path.join(__dirname, "app", "worksheet", "olChikiFont.ts");

const fontData = fs.readFileSync(fontPath);
const base64 = fontData.toString("base64");

const output = `// Auto-generated by convert-font.js — do not edit by hand.
export const olChikiFontBase64 = "${base64}";
`;

fs.writeFileSync(outPath, output);
console.log("Wrote", outPath, "(", (base64.length / 1024).toFixed(0), "KB base64 )");
